version: "3.9"

services:

  file-upload-service:
    image: ghcr.io/manusharma0702/rustyocr-file-split-service:latest
    ports:
      - "8000:8000"
    env_file:
      - ./file-upload-service/.env
    depends_on:
      - aggregator-service

  aggregator-service:
    image: ghcr.io/manusharma0702/rustyocr-aggregator-service:latest
    env_file:
      - ./aggregator-service/.env
    depends_on:
      - file-split-service
      - job-queue
      - ocr-service

  file-split-service:
    image: ghcr.io/manusharma0702/rustyocr-file-split-service:latest
    env_file:
      - ./file-split-service/.env

  job-queue:
    image: ghcr.io/manusharma0702/rustyocr-job-queue:latest
    env_file:
      - ./job-queue/.env

  ocr-service:
    image: ghcr.io/manusharma0702/rustyocr-ocr-service:latest
    env_file:
      - ./ocr-service/.env
  ui:
    image: ghcr.io/manusharma0702/rustyocr-ui:latest
    env_file:
      - ./ui/.env
    ports:
      - "3000:80"

